### ISSUE TITLE
萌新求教，跑了两个小时后出现这些错误，是哪里不对啊？

### ISSUE THREAD

**Issue by TripleHack** [YouChouNoBB/2018-tencent-ad-competition-baseline#11]
Traceback (most recent call last):
  File "E:/2018-tencent-ad-competition-baseline-master/bryan_baseline_v2.py", line 76, in batch_predict
    data[feature] = LabelEncoder().fit_transform(data[feature].apply(int))
  File "E:\ProgramData\Anaconda3\lib\site-packages\pandas\core\series.py", line 2551, in apply
    mapped = lib.map_infer(values, f, convert=convert_dtype)
  File "pandas/_libs/src/inference.pyx", line 1521, in pandas._libs.lib.map_infer
ValueError: invalid literal for int() with base 10: '1 2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/2018-tencent-ad-competition-baseline-master/bryan_baseline_v2.py", line 115, in <module>
    result.append(batch_predict(slice,i))
  File "E:/2018-tencent-ad-competition-baseline-master/bryan_baseline_v2.py", line 78, in batch_predict
    data[feature] = LabelEncoder().fit_transform(data[feature])
  File "E:\ProgramData\Anaconda3\lib\site-packages\sklearn\preprocessing\label.py", line 112, in fit_transform
    self.classes_, y = np.unique(y, return_inverse=True)
  File "E:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py", line 210, in unique
    return _unique1d(ar, return_index, return_inverse, return_counts)
  File "E:\ProgramData\Anaconda3\lib\site-packages\numpy\lib\arraysetops.py", line 274, in _unique1d
    perm = ar.argsort(kind='mergesort' if return_index else 'quicksort')
TypeError: '<' not supported between instances of 'int' and 'str'

Process finished with exit code 1

**Comment by Hao-HOU** [comment]
你的这个问题解决了吗？我也遇到了同样的问题。

**Comment by hecomlilong** [comment]
+1

**Comment by hecomlilong** [comment]
这个问题可以直接忽略，我又原封不动再跑一次就不会出现这个错误了。
